#!/bin/bash

if [ -z "$1" ]; then
	echo Please specify a domain to add.
	echo Example: add_mail_domain example.com
	exit 1
fi

echo -e "$1\t\tOK" >>/etc/vmail/domains
postmap /etc/vmail/domains
mkdir /var/vmail/$1
chown vmail:vmail /var/vmail/$1
postfix reload

echo Domain added.