#!/bin/bash

if [ -z "$1" ]; then
	echo Please specify a user to change password for.
	echo Example: change_mail_password martha@example.com
	exit 1
fi


if ! grep "^$1:" /etc/vmail/passwd &>/dev/null; then
	echo This user does not exist.
	exit 1
fi

PASSHASH=$(doveadm pw -s SHA512-CRYPT)
sed -i -e "/$1:.*$/d" /etc/vmail/passwd
echo "$1:$PASSHASH" >> /etc/vmail/passwd
postfix reload
dovecot reload

PASSHASH=""

echo Password changed.